{% set name = "libcxx" %}
{% set version = "3.9.1" %}
{% set sha256 = "25e615e428f60e651ed09ffd79e563864e3f4bc69a9e93ee41505c419d1a7461" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/{{ name }}-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  features:   # [win]
    - vc14    # [win]
  skip: true  # [py<36]

requirements:
  build:
    - toolchain
    - cmake >=3.4.3
    # Needed to unpack the source tarball
    - m2-xz  # [win32]
    - m2w64-xz  # [win64]

    - system  # [linux and not armv7l]

    # "compiling .pyc files" fails without this:
    - python                                # [not win]
    - python {{ environ['PY_VER'] + '*' }}  # [win]

    - clangdev =={{ version }}

  run:
    - system  # [linux and not armv7l]
    - clangdev =={{ version }}

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]

  commands:
    - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1     # [win]

    - test -f $PREFIX/include/c++/v1/iterator      # [unix]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
