{% set version = "20.1.8" %}

{% if sys_abi is undefined %}
{% set sys_abi = "dummy" %}
{% set hardening = "dummy" %}
{% endif %}

package:
  name: libcxx_and_libcxxabi
  version: {{ version }}

source:
  - url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version.replace(".rc", "-rc") }}.tar.gz
    sha256: a6cbad9b2243b17e87795817cfff2107d113543a12486586f8a055a2bb044963
    patches:
      # See https://discourse.llvm.org/t/shipping-custom-libc-on-macos/58606
      - patches/0001-Fix-ABI-compatibility-with-system.patch    # [sys_abi == "pre-12"]
      - patches/0002-custom-error-message-for-old-sdk.patch
      # disable feature that requires up-to-date libcxxabi, which we don't ship
      - patches/0003-disable-_LIBCPP_AVAILABILITY_HAS_INIT_PRIMARY_EXCEPT.patch
      # work around https://github.com/llvm/llvm-project/issues/90332
      - patches/0004-Work-around-stray-nostdlib-flags-causing-errors-with.patch
      # allow chrono implementation to work on osx
      - patches/0005-patch-__libcpp_tzdb_directory-to-allow-use-on-osx.patch

build:
  number: 1
  skip: true  # [win]
  skip: true  # [ppc64le or aarch64]

# use selectors here so smithy breaks up CI jobs
# [sys_abi]
# [hardening]

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python >3               # [not osx]

outputs:
  - name: libcxx-devel
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}        # [hardening == "none"]
      string: debug_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [hardening == "debug"]
      run_exports:                                      # [hardening == "debug"]
        # packages built with hardened lib must not be installable without extra label
        - libcxx =*=debug*                              # [hardening == "debug"]
    files:
      - include/c++                 # [unix]
      # for C++20 modules, which are installed into $PREFIX/share/libc++
      - share/libc++                # [unix]
      - Library/include/c++         # [win]
      # also for C++20 modules
      - lib/libc++.modules.json     # [unix]
    requirements:
      host:
        - {{ pin_subpackage("libcxx", exact=True) }}
      run:
        # re-enable this for osx once chrono implementation is in shared library
        - tzdata  # [linux]
        - {{ pin_subpackage("libcxx", max_pin=None) }}
      run_constrained:
        - __osx <12     # [osx and (sys_abi == "pre-12")]

    # package for old sys_abi is not installable on macOS-12 image anymore
    {% if sys_abi != "pre-12" %}
    test:
      requires:
        - clang                  # [osx]
        - ld64                   # [osx]
        - cctools                # [osx]
        - llvm-tools             # [osx]
        - {{ compiler('cxx') }}  # [not osx]
        - clangxx                # [not osx]
      files:
        - test_sources
        - compile_test.sh   # [unix]
        - compile_test.bat  # [win]
      commands:
        # Dummy var for different hashes
        - echo {{ dummy_var }}                                    # [osx]
        - echo {{ sys_abi }}                                      # [osx]
        - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1    # [win]
        - test -f $PREFIX/include/c++/v1/iterator                 # [unix]

        # make sure we inserted link to our docs wherever it is necessary;
        # i.e. everywhere there's a string "availability(macos,...,introduced=<ver>)" for osx version >10.13;
        # 'grep -v' inverts the match but returns non-zero exit code if no lines are returned; so we use 'wc -l';
        # we want to have zero lines that don't either: contain our link or are for <=10.13 (lowest occurring in that file is 10.9)
        - if [ 0 -ne $(cat ${PREFIX}/include/c++/v1/__configuration/availability.h | grep "availability(macos" | grep -vE "(conda-forge|10.9|10.1[0-3])" | wc -l) ]; then exit 1; fi  # [osx]
        # !!!!!!!!!!!! README !!!!!!!!!!!!!!!!!!
        # we do not ship libcxxabi on OSX - this breaks exception passing
        - if [ -f $PREFIX/lib/libc++abi.dylib ]; then exit 1; fi  # [osx]
        - test -f $PREFIX/lib/libc++abi.so                        # [linux]

        # for full chrono support, libcxx needs leap-seconds.list, which
        # isn't shipped macos-14 image
        - ls -lL /usr/share/zoneinfo
        # This check is intended to start failing once an image starts shipping
        # that file, so we can re-enable the leapsecond portion of the tzdb-tests
        - if [ 0 -ne $(ls -lL /usr/share/zoneinfo | grep leap-seconds.list | wc -l) ]; then exit 1; fi  # [osx]

        - bash compile_test.sh                                    # [unix]
        - compile_test.bat                                        # [win]

        # presence of std modules
        - test -d $PREFIX/share/libc++                  # [unix]
        - test -f $PREFIX/lib/libc++.modules.json       # [unix]

      # Following 2 projects had issues with libc++, so check them
      # before releasing just to be sure.
      downstreams:              # [osx]
        - python-symengine      # [osx]
        - openturns             # [osx]
    {% endif %}

  - name: libcxx
    build:
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}        # [hardening == "none"]
      string: debug_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [hardening == "debug"]
      run_exports:                                      # [hardening == "debug"]
        # packages built with hardened lib must not be installable without extra label
        - libcxx =*=debug*                              # [hardening == "debug"]
      ignore_run_exports_from:
        # we want to ignore libstdcxx, but not libgcc; the latter also comes in through
        # compiler('c'), and conda keeps that despite ignoring the cxx run-exports
        - {{ compiler('cxx') }}
    files:
      - lib/libc++.so               # [linux]
      - lib/libc++.so.*             # [linux]
      - lib/libc++.dylib            # [osx]
      - lib/libc++.*.dylib          # [osx]
      - Library/bin/c++*.dll        # [win]
      # static libs for cross-compilation, due to lack of host-exports
      - lib/libc++.a                # [unix]
      - lib/libc++experimental.*    # [unix]
      - Library/lib/c++*.lib        # [win]
      - Library/lib/libc++*.lib     # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      run:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [linux]
      run_constrained:
        - sysroot_{{ target_platform }} >={{ c_stdlib_version }}    # [linux]
    test:
      commands:
        # presence of shared & static libraries
        - test -f $PREFIX/lib/libc++.so                 # [linux]
        - test -f $PREFIX/lib/libc++.dylib              # [osx]
        - test -f $PREFIX/lib/libc++.a                  # [unix]
        - test -f $PREFIX/lib/libc++experimental.a      # [unix]
        # absence of headers
        - test ! -d $PREFIX/include/c++                 # [unix]

    {% if sys_abi != "pre-12" %}
      downstreams:              # [osx]
        # test current libcxx against old clang builds;
        # version correspondence is 0.{{ CLANG_MAJOR }}
        # these tests are unusual in that they use -Wl,-rpath, but not -L.
        - libcxx-testing 0.20   # [osx]
        - libcxx-testing 0.19   # [osx]
        - libcxx-testing 0.18   # [osx]
        - libcxx-testing 0.17   # [osx]
        - libcxx-testing 0.16   # [osx]
    {% endif %}

  - name: libcxxabi
    build:
      skip: true  # [not linux]
      # even though libcxxabi shouldn't be affected, distinguish builds
      string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}        # [hardening == "none"]
      string: debug_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [hardening == "debug"]
    files:
      - lib/libc++abi.*
    requirements:
      build:
        # for run-exports
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
      run_constrained:
        - libcxx {{ version }}.*
    test:
      commands:
        - test -f $PREFIX/lib/libc++abi.so  # [linux]

about:
  home: http://libcxx.llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_file: libcxx/LICENSE.TXT
  license_family: Apache
  summary: LLVM C++ standard library
  dev_url: https://github.com/llvm/llvm-project

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - jakirkham
    - isuruf
    - beckermr
    - timsnyder
    - h-vetinari
  feedstock-name: libcxx
