{% set version = "9.0.0" %}

package:
  name: libcxx_and_libcxxabi
  version: {{ version }}

source:
  - url: http://releases.llvm.org/{{ version }}/libcxx-{{ version }}.src.tar.xz
    sha256: 3c4162972b5d3204ba47ac384aa456855a17b5e97422723d4758251acf1ed28c
    patches:
      # See https://bugs.llvm.org/show_bug.cgi?id=39696
      - ppc64le-constexpr.patch  # [ppc64le]
  - url: http://releases.llvm.org/{{ version }}/libcxxabi-{{ version }}.src.tar.xz    # [linux]
    sha256: 675041783565c906ac2f7f8b2bc5c40f14d871ecfa8ade34855aa18de95530e9          # [linux]
    folder: libcxxabi                                                                 # [linux]

build:
  number: 1
  skip: true  # [win]
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - cmake                   # [not osx]
    - cmake-binary            # [osx]
    - make                    # [not osx]
    - {{ compiler('cxx') }}
    - python >3               # [not osx]
  host:
    - clangdev {{ version }}  # [not osx]
    - llvmdev {{ version }}   # [not osx]

test:
  commands:
    # this is not run but instead exists to make the conda-forge linter happy
    - foo

outputs:
  - name: libcxx
    files:
      - include/c++
      - Library/include/c++
      - lib/libc++.*
      - lib/libc++fs.*
      - lib/libc++experimental.*
      - Library/bin/c++*.dll
      - Library/lib/c++*.lib
      - Library/lib/libc++*.lib
      - lib/libc++abi.*  # [not osx]
    test:
      requires:
        - clang {{ version }}
        - clangxx {{ version }}
        - {{ compiler('cxx') }}  # [not osx]
      script: compile_test.sh   # [unix]
      files:
        - test_sources

      # Following 2 projects had issues with libc++, so check them
      # before releasing just to be sure.
      downstreams:          # [osx]
        - python-symengine  # [osx]
        - openturns         # [osx]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
    - jakirkham
    - isuruf
