{% set name = "libcxx" %}
{% set version = "4.0.0" %}
{% set build_number = "1" %}
{% set sha256 = "4f4d33c4ad69bf9e360eebe6b29b7b19486948b1a41decf89d4adec12473cf96" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/{{ name }}-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  skip: true  # [(unix and py3k) or (win and py<36)]
  features:   # [win and py36]
    - vc14    # [win and py36]

requirements:
  build:
    - toolchain
    - cmake >=3.4.3
    # Needed to unpack the source and patch it.
    - m2-tar                                # [win]
    - m2-xz                                 # [win]
    - m2-patch                              # [win]

    - system  # [linux and not armv7l]

    # "compiling .pyc files" fails without this:
    - python

    - msinttypes  # [win]
    - dirent      # [win]
    - clangdev =={{ version }}
    - curl

  run:
    - system  # [linux and not armv7l]
    - clangdev =={{ version }}

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
  files:
    - test_sources
    - compile_test.sh

  commands:
    - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1     # [win]

    - test -f $PREFIX/include/c++/v1/iterator      # [unix]

    - bash compile_test.sh   # [unix]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
    - jakirkham
    - isuruf
