{% set name = "libcxx" %}
{% set version = "6.0.0" %}
{% set build_number = "1" %}
{% set sha256 = "70931a87bde9d358af6cb7869e7535ec6b015f7e6df64def6d2ecdd954040dd9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/{{ name }}-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  merge_build_host: true

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    # "compiling .pyc files" fails without this
    - python
    - clangdev =={{ version }}
    # For downloading libcxxabi
    - curl
  host: []

  # llvm-meta pins compatibility version
  # if clangdev, etc. are installed
  # without pulling them in as dependencies
  run:
    - llvm-meta =={{ version }}

test:
  requires:
    - {{ compiler('cxx') }}  # [win]
    - clangdev
  files:
    - test_sources
    - compile_test.sh   # [unix]
    - compile_test.bat  # [win]

  commands:
    - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1     # [win]

    - test -f $PREFIX/include/c++/v1/iterator      # [unix]

    - bash compile_test.sh   # [unix]
    - compile_test.bat       # [win]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
    - jakirkham
    - isuruf
