{% set version = "8.0.0" %}

package:
  name: libcxx_and_libcxxabi
  version: {{ version }}

source:
  - url: http://llvm.org/releases/{{ version }}/libcxx-{{ version }}.src.tar.xz
    sha256: c2902675e7c84324fb2c1e45489220f250ede016cc3117186785d9dc291f9de2
    patches:
      - install_dll.diff
      # See https://bugs.llvm.org/show_bug.cgi?id=39696
      - ppc64le-constexpr.patch  # [ppc64le]

  - url: http://llvm.org/releases/{{ version }}/libcxxabi-{{ version }}.src.tar.xz    # [unix]
    sha256: c2d6de9629f7c072ac20ada776374e9e3168142f20a46cdb9d6df973922b07cd          # [unix]
    folder: libcxxabi                                                                 # [unix]

build:
  number: 4
  skip: true  # [win and vc<14]
  skip: true  # [win]
  ignore_run_exports:
    - libstdcxx-ng

requirements:
  build:
    - cmake                   # [not osx]
    - cmake-binary            # [osx]
    - make                    # [not osx]
    - {{ compiler('cxx') }}   # [not osx]
    - python >3               # [not osx]
  host:
    - clangdev {{ version }}  # [not osx]
    - llvmdev {{ version }}   # [not osx]

test:
  requires:
    - clangdev
    - {{ compiler('cxx') }}  # [not osx]
  files:
    - test_sources
    - compile_test.sh   # [unix]
    - compile_test.bat  # [win]
  commands:
    - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1     # [win]
    - test -f $PREFIX/include/c++/v1/iterator      # [unix]
    - bash compile_test.sh   # [unix and cxx_compiler!='gxx']
    - compile_test.bat       # [win]

  # Following 2 projects had issues with libc++, so check them
  # before releasing just to be sure.
  downstreams:          # [osx]
    - python-symengine  # [osx]
    - openturns         # [osx]

outputs:
  - name: libcxx
    files:
      - include/c++
      - Library/include/c++
      - lib/libc++.*
      - lib/libc++fs.*
      - lib/libc++experimental.*
      - Library/bin/c++*.dll
      - Library/lib/c++*.lib
      - Library/lib/libc++*.lib
    requirements:
      run:
        - {{ pin_subpackage("libcxxabi", exact=True) }}    # [unix]

  - name: libcxxabi
    build:
      skip: True       # [not unix]
    files:
      - lib/libc++abi.*
    requirements:
      run_constrained:
        - {{ pin_subpackage("libcxx", exact=True) }}

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
    - jakirkham
    - isuruf
