azure:
  settings_osx:
    pool:
      vmImage: macos-14
bot:
  abi_migration_branches:
  - 20.x
  - 19.x
build_platform:
  osx_arm64: osx_64
  win_arm64: win_64
channel_priority: flexible
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
