azure:
  settings_osx:
    pool:
      vmImage: macos-14
bot:
  abi_migration_branches:
  - 18.x
  - 17.x
build_platform:
  osx_arm64: osx_64
channel_priority: flexible
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
