bot:
  abi_migration_branches:
  - 15.x
  - 14.x
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  osx_image: xcode6.4
conda_forge_output_validation: true
build_platform:
  osx_arm64: osx_64
channel_priority: flexible
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
