azure:
  settings_osx:
    pool:
      vmImage: macos-14
bot:
  abi_migration_branches:
  - 16.x
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
channel_priority: flexible
github:
  branch_name: main
  tooling_branch_name: main
remote_ci_setup:
# https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/342
- conda-forge-ci-setup<4.9
- conda-build>=24.1
test: native_and_emulated
